### ISSUE TITLE
Mettre à disposition votre container (Docker Hub / Registry)

### ISSUE THREAD

**Issue by Zennael** [NicolasW-7/AIS-Brief-et-TIPS#16]

**Comment by Zennael** [comment]
![Image](https://github.com/NicolasW-7/AIS-Brief-et-TIPS/assets/146722749/2ca8d563-08ad-47fc-8e93-450b23bdeb54)

**Comment by Jrb62** [comment]
![Image](https://github.com/NicolasW-7/AIS-Brief-et-TIPS/assets/98950407/cf6f32cf-e096-4ce9-8577-f120ce946f2c)
