### ISSUE TITLE
Tester le conteneur localement

### ISSUE THREAD

**Issue by Zennael** [NicolasW-7/AIS-Brief-et-TIPS#5]

**Comment by Zennael** [comment]
![Image](https://github.com/NicolasW-7/AIS-Brief-et-TIPS/assets/146722749/3e08498e-1300-4fe7-9f74-d6a0acb98aea)

**Comment by Zennael** [comment]
![Image](https://github.com/NicolasW-7/AIS-Brief-et-TIPS/assets/146722749/8c874eb6-be9d-442f-85ed-f42c5ff0b9ed)

**Comment by Ariyu-M** [comment]
test
